-- Add your SQL here
CREATE TABLE Orders (
    ID INTEGER PRIMARY KEY,
    CUSTOMER_ID INTEGER UNIQUE NOT NULL,
    TOTAL_AMOUNT REAL NOT NULL CHECK(TOTAL_AMOUNT >= 0),
    ORDER_STATUS TEXT NOT NULL DEFAULT 'Pending',
    SHIPPING_FEE REAL CHECK(SHIPPING_FEE >= 2),
    PAYMENT_METHOD TEXT NOT NULL,
    PAID INTEGER
);